In [1]:
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import re

In [2]:
finviz_url = 'https://finviz.com/quote.ashx?t='
#tickers = ['META','AMZN','AAPL','ABNB','ADBE','ADI','ADP','ADSK','AEP','ALGN','AMAT','AMD','AMGN','BKNG','CDNS','CEG','CHTR','CMCSA','COST','CPRT','CRWD','CSCO','CSX','CTAS','CTSH','DDOG','DLTR'
#,'DOCU','DXCM','EA','EBAY','EXC','FAST','FISV','FTNT','GILD','GOOG','GOOGL','HON','IDXX','ILMN','INTC','INTU','ISRG','JD','KDP','KHC'
#,'KLAC','LCID','LRCX','LULU','MAR','MCHP','MDLZ','MELI','MNST','MRNA','MRVL','MSFT','MTCH','MU','NFLX','NTES','NVDA','NXPI','ODFL','OKTA','ORLY','PANW','PAYX','PCAR','PDD','PEP','PYPL','QCOM'
#,'REGN','ROST','SBUX','SGEN','SIRI','SNPS','SPLK','SWKS','TEAM','TMUS','TSLA','TXN','VRSK','VRSN','VRTX','WBA','WDAY','XEL','ZM','ZS']

tickers = ['AMZN']

In [3]:
news_tables = {}
for ticker in tickers:
    url = finviz_url + ticker

    req = Request(url=url, headers={'user-agent': 'my-app'})
    response = urlopen(req)

    html = BeautifulSoup(response, features='html.parser')
    news_table = html.find(id='news-table')
    news_tables[ticker] = news_table

parsed_data = []
title_data = []

In [4]:
for ticker, news_table in news_tables.items():

    for row in news_table.findAll('tr'):

        title = row.a.text
        date_data = row.td.text.split(' ')

        if len(date_data) == 1:
            time = date_data[0]
        else:
            date = date_data[0]
            time = date_data[1]
            

        parsed_data.append([ticker, date, time, title])
        title_data.append([title])

df = pd.DataFrame(parsed_data, columns=['ticker', 'date', 'time', 'title'])

In [5]:
df

,ticker,date,time,title
0,AMZN,Aug-01-22,06:00AM,Why being an investor feels terrible right now...
1,AMZN,Aug-01-22,05:57AM,3 Growth Stocks Down 25% to 71% to Buy in August
2,AMZN,Aug-01-22,05:21AM,These 4 Companies Could Be the Next Stock-Spli...
3,AMZN,Aug-01-22,05:06AM,3 Warren Buffett Stocks to Buy Hand Over Fist ...
4,AMZN,Aug-01-22,04:10AM,10 Day Trading Tips for Beginners
...,...,...,...,...
95,AMZN,Jul-28-22,05:22PM,Amazon warns of hiring slowdown after second c...
96,AMZN,Jul-28-22,05:21PM,Amazon beats sales estimates but ends another ...
97,AMZN,Jul-28-22,05:06PM,Amazon Stock Jumps As Second-Quarter Revenue B...
98,AMZN,Jul-28-22,05:02PM,"Stocks to watch in after-hours: Apple, Amazon,..."
99,AMZN,Jul-28-22,04:42PM,Amazon can 'subsidize the retail business as t...

In [6]:
def cleanTwt(twt):
  twt = re.sub('#[A-Za-z0-9]+','',str(twt))
  twt = re.sub('@[A-Za-z0-9]+','',str(twt))
  twt = re.sub('RT[\s]+','',str(twt))
  twt = re.sub('\\n','',str(twt))
  twt = re.sub('https?:\/\/\S+','',str(twt))
  return twt

In [7]:
df['clean_text']= df['title'].apply(cleanTwt)
df.head(5)

,ticker,date,time,title,clean_text
0,AMZN,Aug-01-22,06:00AM,Why being an investor feels terrible right now...,Why being an investor feels terrible right now...
1,AMZN,Aug-01-22,05:57AM,3 Growth Stocks Down 25% to 71% to Buy in August,3 Growth Stocks Down 25% to 71% to Buy in August
2,AMZN,Aug-01-22,05:21AM,These 4 Companies Could Be the Next Stock-Spli...,These 4 Companies Could Be the Next Stock-Spli...
3,AMZN,Aug-01-22,05:06AM,3 Warren Buffett Stocks to Buy Hand Over Fist ...,3 Warren Buffett Stocks to Buy Hand Over Fist ...
4,AMZN,Aug-01-22,04:10AM,10 Day Trading Tips for Beginners,10 Day Trading Tips for Beginners

In [8]:
df["date"] = df['date'].astype(str)+' '+df["time"]

In [9]:
df = df.drop(['time'], axis = 1)

In [10]:
df

,ticker,date,title,clean_text
0,AMZN,Aug-01-22 06:00AM,Why being an investor feels terrible right now...,Why being an investor feels terrible right now...
1,AMZN,Aug-01-22 05:57AM,3 Growth Stocks Down 25% to 71% to Buy in August,3 Growth Stocks Down 25% to 71% to Buy in August
2,AMZN,Aug-01-22 05:21AM,These 4 Companies Could Be the Next Stock-Spli...,These 4 Companies Could Be the Next Stock-Spli...
3,AMZN,Aug-01-22 05:06AM,3 Warren Buffett Stocks to Buy Hand Over Fist ...,3 Warren Buffett Stocks to Buy Hand Over Fist ...
4,AMZN,Aug-01-22 04:10AM,10 Day Trading Tips for Beginners,10 Day Trading Tips for Beginners
...,...,...,...,...
95,AMZN,Jul-28-22 05:22PM,Amazon warns of hiring slowdown after second c...,Amazon warns of hiring slowdown after second c...
96,AMZN,Jul-28-22 05:21PM,Amazon beats sales estimates but ends another ...,Amazon beats sales estimates but ends another ...
97,AMZN,Jul-28-22 05:06PM,Amazon Stock Jumps As Second-Quarter Revenue B...,Amazon Stock Jumps As Second-Quarter Revenue B...
98,AMZN,Jul-28-22 05:02PM,"Stocks to watch in after-hours: Apple, Amazon,...","Stocks to watch in after-hours: Apple, Amazon,..."
99,AMZN,Jul-28-22 04:42PM,Amazon can 'subsidize the retail business as t...,Amazon can 'subsidize the retail business as t...

In [11]:
import datetime
date = 'Jun-22-22 03:18PM'
dt = datetime.datetime.strptime( date, '%b-%d-%y %I:%M%p' )
if dt.year > 2000:
    dt = dt.replace( year=dt.year)
                     
print(dt)

2022-06-22 15:18:00

In [12]:
df["date"]

0     Aug-01-22 06:00AM
1     Aug-01-22 05:57AM
2     Aug-01-22 05:21AM
3     Aug-01-22 05:06AM
4     Aug-01-22 04:10AM
             ...
95    Jul-28-22 05:22PM
96    Jul-28-22 05:21PM
97    Jul-28-22 05:06PM
98    Jul-28-22 05:02PM
99    Jul-28-22 04:42PM
Name: date, Length: 100, dtype: object

In [13]:
import datetime

In [14]:
def convert_date(date):
    dt = datetime.datetime.strptime(date,'%b-%d-%y %I:%M%p ' )
    if dt.year > 2000:
        dt = dt.replace( year=dt.year)
    return dt

In [15]:
df['date']=df['date'].apply(convert_date)

In [17]:
df

,ticker,date,title,clean_text
0,AMZN,2022-08-01 06:00:00,Why being an investor feels terrible right now...,Why being an investor feels terrible right now...
1,AMZN,2022-08-01 05:57:00,3 Growth Stocks Down 25% to 71% to Buy in August,3 Growth Stocks Down 25% to 71% to Buy in August
2,AMZN,2022-08-01 05:21:00,These 4 Companies Could Be the Next Stock-Spli...,These 4 Companies Could Be the Next Stock-Spli...
3,AMZN,2022-08-01 05:06:00,3 Warren Buffett Stocks to Buy Hand Over Fist ...,3 Warren Buffett Stocks to Buy Hand Over Fist ...
4,AMZN,2022-08-01 04:10:00,10 Day Trading Tips for Beginners,10 Day Trading Tips for Beginners
...,...,...,...,...
95,AMZN,2022-07-28 17:22:00,Amazon warns of hiring slowdown after second c...,Amazon warns of hiring slowdown after second c...
96,AMZN,2022-07-28 17:21:00,Amazon beats sales estimates but ends another ...,Amazon beats sales estimates but ends another ...
97,AMZN,2022-07-28 17:06:00,Amazon Stock Jumps As Second-Quarter Revenue B...,Amazon Stock Jumps As Second-Quarter Revenue B...
98,AMZN,2022-07-28 17:02:00,"Stocks to watch in after-hours: Apple, Amazon,...","Stocks to watch in after-hours: Apple, Amazon,..."
99,AMZN,2022-07-28 16:42:00,Amazon can 'subsidize the retail business as t...,Amazon can 'subsidize the retail business as t...